#!/bin/bash

set -e

args=""
port="3000"

[[ " $@ " =~ " -h " ]] || [[ " $@ " =~ " --help " ]] || [[ " $@ " =~ " -v " ]] || [[ " $@ " =~ " --version " ]] && args="$@"

case $1 in
  local)
    case $2 in
      invoke)
        args="${@: 1: $#-1} --docker-volume-basedir $(pwd) ${@: -1}" ;;
      start-api)
        for parm in `seq 3 "$#"`; do
          [[ " ${@: $parm: 1} " =~ " -p " ]] || [[ " ${@: $parm: 1} " =~ " --port " ]] && port="${@: $parm+1: 1}"
          args="$@ --docker-volume-basedir $(pwd)"
          break
        done
        ;;
    esac ;;
  *)
    args="$@"
esac

cmd="docker run -i --rm \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(pwd):/opt/sam \
	-p $port:$port \
	registry.gitlab.com/trustology/collaboration/trustvault/sam"

$cmd $args
